#ifndef PERIPHERAL_H_INCLUDED
#define PERIPHERAL_H_INCLUDED

/** HW Peripherals **/

enum{
	/** GPIO **/
	PERIPHERAL_GPIO_A,
	PERIPHERAL_GPIO_B,
	PERIPHERAL_GPIO_C,
	PERIPHERAL_GPIO_D,
	PERIPHERAL_GPIO_E,
	PERIPHERAL_GPIO_F,
	PERIPHERAL_GPIO_G,
	/** Timer **/
	PERIPHERAL_TIMER_0,
	PERIPHERAL_TIMER_1,
	PERIPHERAL_TIMER_2,
	PERIPHERAL_TIMER_3,
	/** UART **/
	PERIPHERAL_UART_0,
	PERIPHERAL_UART_1,
	/** I2C **/
	PERIPHERAL_I2C_0,
	/** SPI **/
	PERIPHERAL_SPI_0,
	/** External Interrupt **/
	PERIPHERAL_INT_0,
	PERIPHERAL_INT_1,
	PERIPHERAL_INT_2,
	PERIPHERAL_INT_3,
	PERIPHERAL_INT_4,
	PERIPHERAL_INT_5,
	PERIPHERAL_INT_6,
	PERIPHERAL_INT_7,
	/** ADC **/
	PERIPHERAL_ADC_0,
};


#endif // PERIPHERAL_H_INCLUDED
